USE QLBongDa
GRANT CREATE TABLE TO BDU01;
GO

USE QLBongDa;

GRANT UPDATE ON SCHEMA::dbo TO BDU02;
DENY INSERT, DELETE ON SCHEMA::dbo TO BDU02;
GO

USE QLBongDa;

GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.CauLacBo TO BDU03;
GO

USE QLBongDa;

GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.CAUTHU TO BDU04;
DENY SELECT ON dbo.CAUTHU(NGAYSINH) TO BDU04;
DENY UPDATE ON dbo.CAUTHU(VITRI) TO BDU04;
GO

USE master;
GRANT ALTER TRACE TO BDProfile;