USE QLBongDa
GO

-- 1
IF EXISTS (SELECT * FROM sys.views WHERE name = 'vCau1')
BEGIN
    DROP VIEW vCau1;
END
GO

CREATE VIEW vCau1 AS
SELECT CT.MACT,
	   CT.HOTEN,
	   CT.NGAYSINH,
	   CT.DIACHI,
	   CT.VITRI
FROM CAUTHU CT
	 JOIN CAULACBO CLB ON CT.MACLB = CLB.MACLB
	 JOIN QUOCGIA QG ON QG.MAQG = CT.MAQG
WHERE CLB.TenCLB = N'SHB Đà Nẵng' 
	  AND QG.TENQG = 'Brazil';
GO

-- 2
IF EXISTS (SELECT * FROM sys.views WHERE name = 'vCau2')
BEGIN
    DROP VIEW vCau2;
END
GO

CREATE VIEW vCau2 AS
SELECT TD.MATRAN, TD.NGAYTD, SVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TD.KETQUA
FROM TRANDAU TD
JOIN CAULACBO CLB1 ON TD.MACLB1 = CLB1.MACLB
JOIN CAULACBO CLB2 ON TD.MACLB2 = CLB2.MACLB
JOIN SANVD SVD ON TD.MASAN = SVD.MASAN
WHERE TD.VONG = 3 AND TD.NAM = 2009;
GO

-- 3
IF EXISTS (SELECT * FROM sys.views WHERE name = 'vCau3')
BEGIN
    DROP VIEW vCau3;
END
GO

CREATE VIEW vCau3 AS
SELECT HLV.MAHLV, HLV.TENHLV, HLV.NGAYSINH, HLV.DIACHI, HC.VAITRO, CLB.TENCLB
FROM HUANLUYENVIEN HLV
	 JOIN HLV_CLB HC ON HLV.MAHLV = HC.MAHLV
	 JOIN CAULACBO CLB ON CLB.MACLB = HC.MACLB
	 JOIN QUOCGIA QG ON QG.MAQG = HLV.MAQG
WHERE QG.TENQG = N'Việt Nam'
GO

-- 4
IF EXISTS (SELECT * FROM sys.views WHERE name = 'vCau4')
BEGIN
    DROP VIEW vCau4;
END
GO

CREATE VIEW vCau4 AS
SELECT CLB.MACLB, CLB.TENCLB, SVD.TENSAN, SVD.DIACHI, COUNT(*) AS SO_CAU_THU_NUOC_NGOAI
FROM CAUTHU
JOIN CAULACBO CLB ON CAUTHU.MACLB = CLB.MACLB
JOIN SANVD SVD ON CLB.MASAN = SVD.MASAN
JOIN QUOCGIA QG ON CAUTHU.MAQG = QG.MAQG
WHERE QG.TENQG <> N'Việt Nam'
GROUP BY CLB.MACLB, CLB.TENCLB, SVD.TENSAN, SVD.DIACHI
HAVING COUNT(*) > 2;
GO

-- 5
IF EXISTS (SELECT * FROM sys.views WHERE name = 'vCau5')
BEGIN
    DROP VIEW vCau5;
END
GO

CREATE VIEW vCau5 AS
SELECT T.TENTINH, ISNULL(COUNT(DISTINCT CT.MACT), 0) AS SoLuong
FROM TINH T
    LEFT JOIN CAULACBO CLB ON T.MATINH = CLB.MATINH
    LEFT JOIN CAUTHU CT ON CLB.MaCLB = CT.MaCLB AND CT.VITRI = N'Tiền đạo'
GROUP BY T.TENTINH
GO

-- 6
IF EXISTS (SELECT * FROM sys.views WHERE name = 'vCau6')
BEGIN
    DROP VIEW vCau6;
END
GO

CREATE VIEW vCau6 AS
SELECT TOP 1 CLB.TENCLB, TINH.TENTINH
FROM BANGXH BXH
JOIN CAULACBO CLB ON BXH.MACLB = CLB.MACLB
JOIN TINH ON CLB.MATINH = TINH.MATINH
WHERE BXH.VONG = 3 AND BXH.NAM = 2009
ORDER BY BXH.HANG ASC
GO

-- 7
IF EXISTS (SELECT * FROM sys.views WHERE name = 'vCau7')
BEGIN
    DROP VIEW vCau7;
END
GO

CREATE VIEW vCau7 AS
SELECT HLV.TENHLV
FROM HUANLUYENVIEN HLV
	 JOIN HLV_CLB HC ON HC.MAHLV = HLV.MAHLV
	 JOIN CAULACBO CLB ON HC.MACLB = CLB.MaCLB
WHERE HLV.DIENTHOAI IS NULL;
GO

-- 8
IF EXISTS (SELECT * FROM sys.views WHERE name = 'vCau8')
BEGIN
    DROP VIEW vCau8;
END
GO

CREATE VIEW vCau8 AS
SELECT HLV.MAHLV, HLV.TENHLV, HLV.NGAYSINH, HLV.DIACHI
FROM HUANLUYENVIEN HLV
JOIN QUOCGIA QG ON HLV.MAQG = QG.MAQG
WHERE QG.TENQG = N'Việt Nam' AND MAHLV NOT IN (SELECT MAHLV FROM HLV_CLB);
GO

-- 9
IF EXISTS (SELECT * FROM sys.views WHERE name = 'vCau9')
BEGIN
    DROP VIEW vCau9;
END
GO

CREATE VIEW vCau9 AS
SELECT TD.NGAYTD, SVD.TENSAN, CLB1.TENCLB AS TEN_CLB1, CLB2.TENCLB AS TEN_CLB2, TD.KETQUA
FROM TRANDAU TD
	 JOIN SANVD SVD ON TD.MASAN = SVD.MASAN
	 JOIN CAULACBO CLB1 ON CLB1.MACLB = TD.MACLB1
	 JOIN CAULACBO CLB2 ON CLB2.MACLB = TD.MACLB2
WHERE TD.MACLB1 = (
		SELECT TOP 1 MACLB FROM BANGXH 
		WHERE VONG = 3 AND NAM = 2009 
		ORDER BY HANG ASC
	) OR TD.MACLB2 = (
	SELECT TOP 1 MACLB FROM BANGXH 
	WHERE VONG = 3 AND NAM = 2009 
	ORDER BY HANG ASC
);

GO

-- 10
IF EXISTS (SELECT * FROM sys.views WHERE name = 'vCau10')
BEGIN
    DROP VIEW vCau10;
END
GO

CREATE VIEW vCau10 AS
SELECT TD.NGAYTD, SVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TD.KETQUA
FROM TRANDAU TD
JOIN CAULACBO CLB1 ON TD.MACLB1 = CLB1.MACLB
JOIN CAULACBO CLB2 ON TD.MACLB2 = CLB2.MACLB
JOIN SANVD SVD ON TD.MASAN = SVD.MASAN
WHERE TD.MACLB1 = (SELECT TOP 1 MACLB FROM BANGXH WHERE VONG = 3 AND NAM = 2009 ORDER BY HANG DESC)
   OR TD.MACLB2 = (SELECT TOP 1 MACLB FROM BANGXH WHERE VONG = 3 AND NAM = 2009 ORDER BY HANG DESC);
GO

-- Cấp quyền
-- BDRead
GRANT SELECT ON vCau1 TO BDRead;
GRANT SELECT ON vCau2 TO BDRead;
GRANT SELECT ON vCau3 TO BDRead;
GRANT SELECT ON vCau4 TO BDRead;
GRANT SELECT ON vCau5 TO BDRead;
GRANT SELECT ON vCau6 TO BDRead;
GRANT SELECT ON vCau7 TO BDRead;
GRANT SELECT ON vCau8 TO BDRead;
GRANT SELECT ON vCau9 TO BDRead;
GRANT SELECT ON vCau10 TO BDRead;

--BDU01
GRANT SELECT ON vCau5 TO BDU01;
GRANT SELECT ON vCau6 TO BDU01;
GRANT SELECT ON vCau7 TO BDU01;
GRANT SELECT ON vCau8 TO BDU01;
GRANT SELECT ON vCau9 TO BDU01;
GRANT SELECT ON vCau10 TO BDU01;

--BDU03
GRANT SELECT ON vCau1 TO BDU03;
GRANT SELECT ON vCau2 TO BDU03;
GRANT SELECT ON vCau3 TO BDU03;
GRANT SELECT ON vCau4 TO BDU03;

--BDU04
GRANT SELECT ON vCau1 TO BDU04;
GRANT SELECT ON vCau2 TO BDU04;
GRANT SELECT ON vCau3 TO BDU04;
GRANT SELECT ON vCau4 TO BDU04;
