USE QLBongDa
GO

-- SP 1
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SPCau1')
BEGIN
    DROP PROCEDURE SPCau1;
END
GO

CREATE PROCEDURE SPCau1  
	@TenCLB NVARCHAR(100),
	@TenQG NVARCHAR(60)
AS
BEGIN
    SELECT CT.MACT, CT.HOTEN, CT.NGAYSINH, CT.DIACHI, CT.VITRI
    FROM CAUTHU CT
        JOIN CAULACBO CLB ON CT.MACLB = CLB.MACLB
        JOIN QUOCGIA QG ON QG.MAQG = CT.MAQG
    WHERE CLB.TenCLB = @TenCLB 
          AND QG.TENQG = @TenQG;
END
GO
 
-- SP 2
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SPCau2')
BEGIN
    DROP PROCEDURE SPCau2;
END
GO

CREATE PROCEDURE SPCau2 
    @Vong INT,
    @Nam INT
AS
BEGIN
    SELECT TD.MATRAN, TD.NGAYTD, SVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TD.KETQUA
    FROM TRANDAU TD
    JOIN CAULACBO CLB1 ON TD.MACLB1 = CLB1.MACLB
    JOIN CAULACBO CLB2 ON TD.MACLB2 = CLB2.MACLB
    JOIN SANVD SVD ON TD.MASAN = SVD.MASAN
    WHERE TD.VONG = @Vong AND TD.NAM = @Nam;
END;
GO

-- SP 3
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SPCau3')
BEGIN
    DROP PROCEDURE SPCau3;
END
GO

CREATE PROCEDURE SPCau3
    @TenQG NVARCHAR(60)
AS
BEGIN
    SELECT HLV.MAHLV, HLV.TENHLV, HLV.NGAYSINH, HLV.DIACHI, HC.VAITRO, CLB.TENCLB
    FROM HUANLUYENVIEN HLV
        JOIN HLV_CLB HC ON HLV.MAHLV = HC.MAHLV
        JOIN CAULACBO CLB ON CLB.MACLB = HC.MACLB
        JOIN QUOCGIA QG ON QG.MAQG = HLV.MAQG
    WHERE QG.TENQG = @TenQG;
END
GO

-- SP 4
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SPCau4')
BEGIN
    DROP PROCEDURE SPCau4;
END
GO

CREATE PROCEDURE SPCau4 
    @TenQuocGia NVARCHAR(60),
    @SoLuong INT
AS
BEGIN
    SELECT CLB.MACLB, CLB.TENCLB, SVD.TENSAN, SVD.DIACHI, COUNT(*) AS SO_CAU_THU_NUOC_NGOAI
    FROM CAUTHU
    JOIN CAULACBO CLB ON CAUTHU.MACLB = CLB.MACLB
    JOIN SANVD SVD ON CLB.MASAN = SVD.MASAN
	JOIN QUOCGIA QG ON QG.MAQG = CAUTHU.MAQG
    WHERE QG.TENQG <> @TenQuocGia
    GROUP BY CLB.MACLB, CLB.TENCLB, SVD.TENSAN, SVD.DIACHI
    HAVING COUNT(*) > @SoLuong;
END;
GO

-- SP 5
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SPCau5')
BEGIN
    DROP PROCEDURE SPCau5;
END
GO

CREATE PROCEDURE SPCau5
    @ViTri NVARCHAR(20)
AS
BEGIN
    SELECT T.TENTINH, ISNULL(COUNT(DISTINCT CT.MACT), 0) AS SoLuong
FROM TINH T
    LEFT JOIN CAULACBO CLB ON T.MATINH = CLB.MATINH
    LEFT JOIN CAUTHU CT ON CLB.MaCLB = CT.MaCLB AND CT.VITRI = N'Tiền đạo'
GROUP BY T.TENTINH
END
GO

-- SP 6
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SPCau6')
BEGIN
    DROP PROCEDURE SPCau6;
END
GO

CREATE PROCEDURE SPCau6 
    @Vong INT,
    @Nam INT
AS
BEGIN
    SELECT TOP 1 CLB.TENCLB, TINH.TENTINH
    FROM BANGXH BXH
    JOIN CAULACBO CLB ON BXH.MACLB = CLB.MACLB
    JOIN TINH ON CLB.MATINH = TINH.MATINH
    WHERE BXH.VONG = @Vong AND BXH.NAM = @Nam
    ORDER BY BXH.HANG ASC;
END;
GO

-- SP 7
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SPCau7')
BEGIN
    DROP PROCEDURE SPCau7;
END
GO

CREATE PROCEDURE SPCau7
AS
BEGIN
    SELECT HLV.TENHLV
    FROM HUANLUYENVIEN HLV
        JOIN HLV_CLB HC ON HC.MAHLV = HLV.MAHLV
        JOIN CAULACBO CLB ON HC.MACLB = CLB.MaCLB
    WHERE HLV.DIENTHOAI IS NULL;
END
GO

-- SP 8 
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SPCau8')
BEGIN
    DROP PROCEDURE SPCau8;
END
GO

CREATE PROCEDURE SPCau8 
    @TenQuocGia NVARCHAR(60)
AS
BEGIN
    SELECT HLV.MAHLV, HLV.TENHLV, HLV.NGAYSINH, HLV.DIACHI
    FROM HUANLUYENVIEN HLV
	JOIN QUOCGIA QG ON HLV.MAQG = QG.MAQG
    WHERE QG.TENQG = @TenQuocGia AND MAHLV NOT IN (SELECT MAHLV FROM HLV_CLB);
END;
GO

-- SP 9
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SPCau9')
BEGIN
    DROP PROCEDURE SPCau9;
END
GO

CREATE PROCEDURE SPCau9
    @Vong INT,
    @Nam INT
AS
BEGIN
    SELECT TD.NGAYTD, SVD.TENSAN, CLB1.TENCLB AS TEN_CLB1, CLB2.TENCLB AS TEN_CLB2, TD.KETQUA
    FROM TRANDAU TD
        JOIN SANVD SVD ON TD.MASAN = SVD.MASAN
        JOIN CAULACBO CLB1 ON CLB1.MACLB = TD.MACLB1
        JOIN CAULACBO CLB2 ON CLB2.MACLB = TD.MACLB2
    WHERE TD.MACLB1 = (
        SELECT TOP 1 MACLB FROM BANGXH 
        WHERE VONG = @Vong AND NAM = @Nam 
        ORDER BY HANG ASC
    ) OR TD.MACLB2 = (
        SELECT TOP 1 MACLB FROM BANGXH 
        WHERE VONG = @Vong AND NAM = @Nam 
        ORDER BY HANG ASC
    );
END
GO

-- SP 10
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'SPCau10')
BEGIN
    DROP PROCEDURE SPCau10;
END
GO

CREATE PROCEDURE SPCau10 
    @Vong INT,
    @Nam INT
AS
BEGIN
    SELECT TD.NGAYTD, SVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TD.KETQUA
    FROM TRANDAU TD
    JOIN CAULACBO CLB1 ON TD.MACLB1 = CLB1.MACLB
    JOIN CAULACBO CLB2 ON TD.MACLB2 = CLB2.MACLB
    JOIN SANVD SVD ON TD.MASAN = SVD.MASAN
    WHERE TD.MACLB1 = (SELECT TOP 1 MACLB FROM BANGXH WHERE VONG = @Vong AND NAM = @Nam ORDER BY HANG DESC)
       OR TD.MACLB2 = (SELECT TOP 1 MACLB FROM BANGXH WHERE VONG = @Vong AND NAM = @Nam ORDER BY HANG DESC);
END;
GO


-- Phân quyền
-- Cấp quyền
-- BDRead
GRANT EXECUTE ON SPCau1 TO BDRead;
GRANT EXECUTE ON SPCau2 TO BDRead;
GRANT EXECUTE ON SPCau3 TO BDRead;
GRANT EXECUTE ON SPCau4 TO BDRead;
GRANT EXECUTE ON SPCau5 TO BDRead;
GRANT EXECUTE ON SPCau6 TO BDRead;
GRANT EXECUTE ON SPCau7 TO BDRead;
GRANT EXECUTE ON SPCau8 TO BDRead;
GRANT EXECUTE ON SPCau9 TO BDRead;
GRANT EXECUTE ON SPCau10 TO BDRead;

--BDU01
GRANT EXECUTE ON SPCau5 TO BDU01;
GRANT EXECUTE ON SPCau6 TO BDU01;
GRANT EXECUTE ON SPCau7 TO BDU01;
GRANT EXECUTE ON SPCau8 TO BDU01;
GRANT EXECUTE ON SPCau9 TO BDU01;
GRANT EXECUTE ON SPCau10 TO BDU01;

--BDU03
GRANT EXECUTE ON SPCau1 TO BDU03;
GRANT EXECUTE ON SPCau2 TO BDU03;
GRANT EXECUTE ON SPCau3 TO BDU03;
GRANT EXECUTE ON SPCau4 TO BDU03;

--BDU04
GRANT EXECUTE ON SPCau1 TO BDU04;
GRANT EXECUTE ON SPCau2 TO BDU04;
GRANT EXECUTE ON SPCau3 TO BDU04;
GRANT EXECUTE ON SPCau4 TO BDU04;
