--ab.sql
--USE master;
--GO
--ALTER DATABASE QLSVNhom SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
--GO
--DROP DATABASE QLSVNhom;
--GO

USE master;
GO

IF DB_ID('QLSVNhom') IS NOT NULL
BEGIN
    DROP DATABASE QLSVNhom
END
GO 

-- Tạo Database QLSVNhom
CREATE DATABASE QLSVNhom;
GO

USE QLSVNhom;
GO

-- Tạo bảng SINHVIEN
CREATE TABLE SINHVIEN (
    MASV VARCHAR(20) PRIMARY KEY, -- Đã thay đổi kiểu dữ liệu cho phù hơp
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATETIME,
    DIACHI NVARCHAR(200),
    MALOP VARCHAR(20), -- Đã thay đổi kiểu dữ liệu cho phù hơp
    TENDN NVARCHAR(100) NOT NULL UNIQUE,
    MATKHAU VARBINARY(MAX) NOT NULL  -- Lưu giá trị mật khẩu sau khi mã hóa
);

-- Tạo bảng NHANVIEN
CREATE TABLE NHANVIEN (
    MANV VARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    EMAIL VARCHAR(20),
    LUONG VARBINARY(MAX),  -- Lưu giá trị lương sau khi mã hóa
    TENDN NVARCHAR(100) NOT NULL UNIQUE,
    MATKHAU VARBINARY(MAX) NOT NULL,  -- Lưu mật khẩu đã được mã hóa (SHA1)
    PUBKEY VARCHAR(20)  -- Tên khóa công khai, bằng với MANV
);

-- Tạo bảng LOP
CREATE TABLE LOP (
    MALOP VARCHAR(20) PRIMARY KEY,
    TENLOP NVARCHAR(100) NOT NULL,
    MANV VARCHAR(20)  -- Mã nhân viên chủ nhiệm
);

-- Tạo bảng HOCPHAN
CREATE TABLE HOCPHAN (
    MAHP VARCHAR(20) PRIMARY KEY,
    TENHP NVARCHAR(100) NOT NULL,
    SOTC INT
);

-- Tạo bảng BANGDIEM
CREATE TABLE BANGDIEM (
    MASV VARCHAR(20),
    MAHP VARCHAR(20),
    DIEMTHI VARBINARY(MAX),  -- Điểm thi được mã hóa
    PRIMARY KEY (MASV, MAHP)
);

-- Thêm khóa ngoại cho các bảng
ALTER TABLE SINHVIEN
ADD CONSTRAINT FK_SINHVIEN_LOP
FOREIGN KEY (MALOP)
REFERENCES LOP(MALOP);
GO

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_NHANVIEN
FOREIGN KEY (MANV)
REFERENCES NHANVIEN(MANV);
GO

ALTER TABLE BANGDIEM
ADD CONSTRAINT FK_BANGDIEM_SINHVIEN
FOREIGN KEY (MASV)
REFERENCES SINHVIEN(MASV);
GO

ALTER TABLE BANGDIEM
ADD CONSTRAINT FK_BANGDIEM_HOCPHAN
FOREIGN KEY (MAHP)
REFERENCES HOCPHAN(MAHP);
GO