-- d.sql
USE QLSVNhom;
GO

IF OBJECT_ID('SP_GET_SCORES_BY_CLASS', 'P') IS NOT NULL
    DROP PROCEDURE SP_GET_SCORES_BY_CLASS;
GO

CREATE PROCEDURE SP_GET_SCORES_BY_CLASS
    @MALOP VARCHAR(20),
    @PUBKEY VARCHAR(20),
    @ErrorMessage NVARCHAR(200) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM LOP WHERE MALOP = @MALOP)
    BEGIN
        SET @ErrorMessage = 'Mã lớp không tồn tại!';
        RETURN;
    END

    IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE MANV = @PUBKEY)
    BEGIN
        SET @ErrorMessage = 'Mã nhân viên không hợp lệ!';
        RETURN;
    END

    -- Trả dữ liệu điểm ở dạng mã hóa (VARBINARY)
    SELECT 
        S.MASV,
        S.HOTEN,
        B.MAHP,
        H.TENHP,
        B.DIEMTHI AS DIEM_ENCRYPTED
    FROM BANGDIEM B
    JOIN SINHVIEN S ON B.MASV = S.MASV
    JOIN HOCPHAN H ON B.MAHP = H.MAHP
    WHERE S.MALOP = @MALOP;

    SET @ErrorMessage = '';
END;
GO


CREATE PROCEDURE SP_INS_DIEM
    @MASV VARCHAR(20),
    @MAHP VARCHAR(20),
    @DIEMTHI VARBINARY(MAX),
    @ErrorMessage NVARCHAR(200) OUTPUT
AS
BEGIN
    BEGIN TRY
        IF EXISTS (SELECT 1 FROM BANGDIEM WHERE MASV = @MASV AND MAHP = @MAHP)
        BEGIN
            UPDATE BANGDIEM
            SET DIEMTHI = @DIEMTHI
            WHERE MASV = @MASV AND MAHP = @MAHP;
        END
        ELSE
        BEGIN
            INSERT INTO BANGDIEM (MASV, MAHP, DIEMTHI)
            VALUES (@MASV, @MAHP, @DIEMTHI);
        END
        SET @ErrorMessage = '';
    END TRY
    BEGIN CATCH
        SET @ErrorMessage = ERROR_MESSAGE();
    END CATCH
END;

-- Xóa stored procedure nếu đã tồn tại
IF OBJECT_ID('SP_INSERT_STUDENT', 'P') IS NOT NULL
    DROP PROCEDURE SP_INSERT_STUDENT;
GO

CREATE PROCEDURE SP_INSERT_STUDENT
    @MASV VARCHAR(20),
    @HOTEN NVARCHAR(100),
    @NGAYSINH DATETIME,
    @DIACHI NVARCHAR(200),
    @MALOP VARCHAR(20),
    @TENDN NVARCHAR(100),
    @MATKHAU VARBINARY(MAX),  -- Mật khẩu gốc, sẽ được mã hóa
    @ErrorMessage NVARCHAR(200) OUTPUT -- Trả về lỗi nếu có
AS
BEGIN
    BEGIN TRY
        SET NOCOUNT ON;

        IF EXISTS (SELECT 1 FROM SINHVIEN WHERE TENDN = @TENDN)
        BEGIN
            SET @ErrorMessage = 'Tên đăng nhập đã tồn tại!';
            RETURN;
        END

        IF NOT EXISTS (SELECT 1 FROM LOP WHERE MALOP = @MALOP)
        BEGIN
            SET @ErrorMessage = 'Mã lớp không hợp lệ!';
            RETURN;
        END

        -- 5️ Chèn dữ liệu vào bảng SINHVIEN
        INSERT INTO SINHVIEN (MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, MATKHAU)
        VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, @MATKHAU);

        SET @ErrorMessage = '';
    END TRY
    BEGIN CATCH
        -- Xử lý lỗi
        SET @ErrorMessage = ERROR_MESSAGE();
    END CATCH
END;
GO

-- Xóa procedure nếu tồn tại trước khi tạo mới
IF OBJECT_ID('SP_DELETE_STUDENT', 'P') IS NOT NULL
    DROP PROCEDURE SP_DELETE_STUDENT;
GO

CREATE PROCEDURE SP_DELETE_STUDENT
    @MASV NVARCHAR(20),
    @MALOP NVARCHAR(20),
    @ErrorMessage NVARCHAR(200) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    IF NOT EXISTS(SELECT 1 FROM SINHVIEN WHERE MASV = @MASV AND MALOP = @MALOP)
    BEGIN
        SET @ErrorMessage = 'Sinh viên không tồn tại trong lớp.';
        RETURN;
    END

  DELETE FROM BANGDIEM WHERE MASV = @MASV;
    DELETE FROM SINHVIEN
    WHERE MASV = @MASV AND MALOP = @MALOP;

    SET @ErrorMessage = '';
END
GO

-- Xóa procedure nếu tồn tại trước khi tạo mới
IF OBJECT_ID('SP_GENERATE_NEW_STUDENT_ID', 'P') IS NOT NULL
    DROP PROCEDURE SP_GENERATE_NEW_STUDENT_ID;
GO

CREATE PROCEDURE SP_GENERATE_NEW_STUDENT_ID
AS
BEGIN
    DECLARE @NewID INT;
    DECLARE @MaxID NVARCHAR(20);
    SELECT @MaxID = MAX(MASV) FROM SINHVIEN;
    IF @MaxID IS NULL
        SET @NewID = 1;
    ELSE
        SET @NewID = CAST(SUBSTRING(@MaxID, PATINDEX('%[0-9]%', @MaxID), LEN(@MaxID)) AS INT) + 1;
    SELECT 'SV' + RIGHT('000' + CAST(@NewID AS NVARCHAR(10)), 3) AS NewMASV;
END
GO

IF OBJECT_ID('SP_GET_STUDENTS_BY_CLASS', 'P') IS NOT NULL
    DROP PROCEDURE SP_GET_STUDENTS_BY_CLASS;
GO

CREATE PROCEDURE SP_GET_STUDENTS_BY_CLASS
    @MALOP NVARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT MASV, HOTEN, NGAYSINH, DIACHI, MALOP
    FROM SINHVIEN
    WHERE MALOP = @MALOP;
END
GO

-- Xóa procedure nếu tồn tại trước khi tạo mới
IF OBJECT_ID('SP_UPDATE_STUDENT_INFO', 'P') IS NOT NULL
    DROP PROCEDURE SP_UPDATE_STUDENT_INFO;
GO

CREATE PROCEDURE SP_UPDATE_STUDENT_INFO
    @MASV NVARCHAR(20),
    @HOTEN NVARCHAR(100),
    @NGAYSINH DATETIME,
    @DIACHI NVARCHAR(200),
    @OLD_MALOP NVARCHAR(20),
    @NEW_MALOP NVARCHAR(20),
    @ErrorMessage NVARCHAR(200) OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    IF NOT EXISTS(SELECT 1 FROM SINHVIEN WHERE MASV = @MASV AND MALOP = @OLD_MALOP)
    BEGIN
        SET @ErrorMessage = 'Sinh vien khong ton tai trong lop hien tai';
        RETURN;
    END

    IF @NEW_MALOP <> @OLD_MALOP
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM LOP WHERE MALOP = @NEW_MALOP)
        BEGIN
            SET @ErrorMessage = 'Ma lop moi khong ton tai.';
            RETURN;
        END
    END

    UPDATE SINHVIEN
    SET HOTEN = @HOTEN,
        NGAYSINH = @NGAYSINH,
        DIACHI = @DIACHI,
        MALOP = @NEW_MALOP
    WHERE MASV = @MASV AND MALOP = @OLD_MALOP;

    SET @ErrorMessage = '';
END
GO

IF OBJECT_ID('SP_FIND_STUDENT_IN_CLASS', 'P') IS NOT NULL
    DROP PROCEDURE SP_FIND_STUDENT_IN_CLASS;
GO

CREATE PROCEDURE SP_FIND_STUDENT_IN_CLASS
    @MASV NVARCHAR(20),
    @MALOP NVARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT MASV, HOTEN, NGAYSINH, DIACHI, MALOP
    FROM SINHVIEN
    WHERE MASV = @MASV AND MALOP = @MALOP;
END
GO

IF OBJECT_ID('SP_GET_CLASSES', 'P') IS NOT NULL
BEGIN
    DROP PROCEDURE SP_GET_CLASSES;
END;
GO

CREATE PROCEDURE SP_GET_CLASSES
AS
BEGIN
    SELECT MALOP, TENLOP, MANV
    FROM LOP;
END
GO

IF OBJECT_ID('SP_SEARCH_CLASSES', 'P') IS NOT NULL
    DROP PROCEDURE SP_SEARCH_CLASSES;
GO

CREATE PROCEDURE SP_SEARCH_CLASSES
    @MALOP NVARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT MALOP, TENLOP, MANV FROM LOP 
    WHERE MALOP = @MALOP;
END
GO

IF OBJECT_ID('SP_LOGIN_NHANVIEN', 'P') IS NOT NULL
    DROP PROCEDURE SP_LOGIN_NHANVIEN;
GO

CREATE PROCEDURE SP_LOGIN_NHANVIEN
    @MANV VARCHAR(20),
    @MK VARBINARY(MAX) -- SHA1 đã mã hóa base64 từ C#
AS
BEGIN
    SET NOCOUNT ON;

    -- Convert base64 string -> VARBINARY
    DECLARE @MK_BIN VARBINARY(MAX) =
        CONVERT(VARBINARY(MAX), CAST(N'' AS XML).value('xs:base64Binary(sql:variable("@MK"))', 'VARBINARY(MAX)'));

    IF EXISTS (
        SELECT 1 FROM NHANVIEN
        WHERE MANV = @MANV AND MATKHAU = @MK_BIN
    )
    BEGIN
        SELECT MANV, HOTEN, EMAIL
        FROM NHANVIEN
        WHERE MANV = @MANV
    END
    ELSE
    BEGIN
        SELECT NULL AS MANV, NULL AS HOTEN, NULL AS EMAIL
    END
END
GO
